name: roadsos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # GPS
  geolocator: ^14.0.2

  # Permissions
  permission_handler: ^12.0.1

  # Camera
  camera: ^0.11.2+1

  # Image Picker
  image_picker: ^1.2.1

  # Audio
  flutter_sound: ^9.30.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true